WARNING:tensorflow:From /home/phoebe/capstone/PilotNet/src/nets/pilotNet.py:62: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2020-10-22 23:21:54.609733: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-10-22 23:21:54.633313: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-22 23:21:54.633636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.74
pciBusID: 0000:0c:00.0
2020-10-22 23:21:54.634178: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2020-10-22 23:21:54.634549: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2020-10-22 23:21:54.634916: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2020-10-22 23:21:54.635271: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2020-10-22 23:21:54.635624: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2020-10-22 23:21:54.636003: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2020-10-22 23:21:54.638396: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-22 23:21:54.638409: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-10-22 23:21:54.638696: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-10-22 23:21:54.659793: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3892705000 Hz
2020-10-22 23:21:54.660364: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55938db60110 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-22 23:21:54.660383: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-22 23:21:54.780544: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-22 23:21:54.780854: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55938db39b10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-22 23:21:54.780875: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1650, Compute Capability 7.5
2020-10-22 23:21:54.780953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-22 23:21:54.780962: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      
DEBUG:root:Done setting logLevel to 10
INFO:root:Initializing the injector
/home/phoebe/capstone/PilotNet/TensorFI/fiConfig.py:269: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params = yaml.load(pStream, Loader=None)
INFO:root:Modifying graph in session 
INFO:root:Done modification of graph
INFO:root:Initializing the fault injection parameters
DEBUG:root:Initialized config file : FIConfig: {
	faultTypeScalar : None
	faultTypeTensor : bitFlip-element
	injectMap : {<Ops.BIASADD: 'BIASADD'>: 0.5}
	faultSeed : None
	skipCount : 0
 }
INFO:root:Initializing the fault log
INFO:root:Performing monkey patching
INFO:root:Done with init
INFO:root:Turning off injections
INFO:root:No injections: Calling oldRun on Tensor("Mul:0", shape=(?, 1), dtype=float32)
INFO:root:Turning on injections
INFO:root:Calling newRun PilotNet runCount = 1
INFO:root:Tensor("Mul:0", shape=(?, 1), dtype=float32) is not iterable
DEBUG:root:TensorList = [<tf.Tensor 'Mul:0' shape=(?, 1) dtype=float32>]
DEBUG:root:Tensor = Mul:0
DEBUG:root:fiTensor = Tensor("fi_Mul:0", dtype=float32)
DEBUG:root:Calling oldRun on fi_Mul:0
2020-10-22 23:21:54.965262: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-22 23:21:54.965289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Sub  
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:Calling Operator conv2D  
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.SUB is chosen for injection
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:Calling Operator Identity 111 
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
2020-10-22 23:21:54.976288: W tensorflow/core/framework/op_kernel.cc:1639] Unknown: exceptions.AttributeError: 'EagerTensor' object has no attribute 'squeeze'
Traceback (most recent call last):

  File "/home/phoebe/.local/virtualenvs/tensorfi3/lib/python2.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 233, in __call__
    return func(device, token, args)

  File "/home/phoebe/.local/virtualenvs/tensorfi3/lib/python2.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 122, in __call__
    ret = self._func(*args)

  File "/home/phoebe/capstone/PilotNet/TensorFI/injectFault.py", line 556, in injectFaultConv2D
    conv = tf.nn.conv2d(a , b, strides=strides.squeeze().tolist(), padding=padding)

AttributeError: 'EagerTensor' object has no attribute 'squeeze'


DEBUG:root:Calling Operator Sub  
DEBUG:root:Calling Operator Sub  
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:Calling Operator Sub  
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.IDENTITY is chosen for injection
DEBUG:root:	Checking if operation Ops.SUB is chosen for injection
DEBUG:root:	Checking if operation Ops.SUB is chosen for injection
DEBUG:root:	Checking if operation Ops.SUB is chosen for injection
ERROR:root:Encountered exception You must feed a value for placeholder tensor 'Placeholder_2' with dtype float
	 [[node Placeholder_2 (defined at /home/phoebe/.local/virtualenvs/tensorfi3/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for u'Placeholder_2':
  File "./src/run_tensorfi_model_injection.py", line 28, in <module>
    model = PilotNet()
  File "/home/phoebe/capstone/PilotNet/src/nets/pilotNet.py", line 21, in __init__
    self.rate = 1 - tf.compat.v1.placeholder(tf.float32)
  File "/home/phoebe/.local/virtualenvs/tensorfi3/lib/python2.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2619, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/phoebe/.local/virtualenvs/tensorfi3/lib/python2.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6669, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/phoebe/.local/virtualenvs/tensorfi3/lib/python2.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/phoebe/.local/virtualenvs/tensorfi3/lib/python2.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/phoebe/.local/virtualenvs/tensorfi3/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/phoebe/.local/virtualenvs/tensorfi3/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/phoebe/.local/virtualenvs/tensorfi3/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

ERROR:root:Unable to execute run on Tensor("fi_Mul:0", dtype=float32)
INFO:root:Done with newRun PilotNet
Total operations = 268
Input tensor = Tensor("Mul:0", shape=(?, 1), dtype=float32)
golden steering = -2.9350321778710904
predicted steering = None
(0, 1.0)
